# Generated by Django 4.2.3 on 2023-07-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userID", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("done", models.BooleanField()),
                ("regdate", models.DateTimeField(auto_now_add=True)),
                ("moddate", models.DateTimeField()),
            ],
        ),
    ]
